using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI.Extensions;

public class PayoutCalculation : MonoBehaviour
{
    internal const int CurveStepsPerSegment = 8;
    [SerializeField] private float[] x_Offsets = { 0f, 262f, 551f, 840f, 1094f };
    [SerializeField] private int y_Distance = 215;
    [SerializeField] private Transform LineContainer;
    [SerializeField] private GameObject Line_Prefab;
    [SerializeField] private Vector2 InitialLinePosition = new Vector2(-551f, 185.12f);
    GameObject TempObj = null;
    //generate lines at runtime accordingly
    internal void GeneratePayoutLinesBackend(List<int> y_index, int Count, bool isStatic = false)
    {
        GameObject MyLineObj = Instantiate(Line_Prefab, LineContainer);
        MyLineObj.transform.localPosition = new Vector2(InitialLinePosition.x, InitialLinePosition.y);
        UILineRenderer MyLine = MyLineObj.GetComponent<UILineRenderer>();
        for (int i = 0; i < Count; i++)
        {
            var points = new Vector2() { x = x_Offsets[i], y = y_index[i] * -y_Distance };
            var pointlist = new List<Vector2>(MyLine.Points);
            pointlist.Add(points);
            MyLine.Points = pointlist.ToArray();
        }
        var newpointlist = new List<Vector2>(MyLine.Points);
        newpointlist.RemoveAt(0);
        MyLine.Points = newpointlist.ToArray();

        if(isStatic)
        {
            MyLineObj.transform.SetParent(LineContainer.parent, true);
            TempObj = MyLineObj;
        }
    }

    internal IEnumerator AnimatePayoutLineBackend(List<KeyValuePair<int, int>> coordinates, float duration, Color lineColor, Action<int> onPointReached)
    {
        List<Vector2> points = new();
        foreach (KeyValuePair<int, int> coordinate in coordinates)
        {
            int rowIndex = coordinate.Key;
            int columnIndex = coordinate.Value;
            if (columnIndex < 0 || columnIndex >= x_Offsets.Length) continue;
            points.Add(new Vector2(x_Offsets[columnIndex], rowIndex * -y_Distance));
        }

        if (points.Count < 2) yield break;
        List<Vector2> curvedPoints = CreateCurvedPath(points);

        GameObject lineObject = Instantiate(Line_Prefab, LineContainer);
        lineObject.transform.localPosition = InitialLinePosition;
        UILineRenderer line = lineObject.GetComponent<UILineRenderer>();
        line.color = lineColor;
        float drawDuration = Mathf.Max(0.01f, duration);
        float elapsed = 0f;
        int reachedPoint = 0;
        onPointReached?.Invoke(0);

        while (elapsed < drawDuration)
        {
            elapsed += Time.deltaTime;
            float pathProgress = Mathf.Clamp01(elapsed / drawDuration) * (curvedPoints.Count - 1);
            int pathIndex = Mathf.Min(Mathf.FloorToInt(pathProgress), curvedPoints.Count - 2);
            float pointProgress = pathProgress - pathIndex;
            List<Vector2> visiblePoints = curvedPoints.GetRange(0, pathIndex + 1);
            visiblePoints.Add(Vector2.Lerp(curvedPoints[pathIndex], curvedPoints[pathIndex + 1], pointProgress));
            line.Points = visiblePoints.ToArray();

            int reachedWaypoint = Mathf.Min(points.Count - 1, Mathf.FloorToInt(pathProgress / CurveStepsPerSegment));
            while (reachedPoint < reachedWaypoint)
                onPointReached?.Invoke(++reachedPoint);

            yield return null;
        }

        line.Points = curvedPoints.ToArray();
        while (reachedPoint < points.Count - 1)
            onPointReached?.Invoke(++reachedPoint);
        yield return new WaitForSeconds(0.3f);
        Destroy(lineObject);
        yield return null;
    }

    internal List<Vector2> CreateCurvedPath(List<Vector2> points)
    {
        if (points.Count < 2) return new List<Vector2>(points);

        List<Vector2> curvedPoints = new() { points[0] };
        for (int segment = 0; segment < points.Count - 1; segment++)
        {
            Vector2 p0 = segment > 0 ? points[segment - 1] : points[segment];
            Vector2 p1 = points[segment];
            Vector2 p2 = points[segment + 1];
            Vector2 p3 = segment + 2 < points.Count ? points[segment + 2] : points[segment + 1];

            for (int step = 1; step <= CurveStepsPerSegment; step++)
            {
                float t = step / (float)CurveStepsPerSegment;
                float t2 = t * t;
                float t3 = t2 * t;
                curvedPoints.Add(0.5f * ((2f * p1) + (-p0 + p2) * t +
                    (2f * p0 - 5f * p1 + 4f * p2 - p3) * t2 +
                    (-p0 + 3f * p1 - 3f * p2 + p3) * t3));
            }
        }

        return curvedPoints;
    }

    //delete the line generated by button hover
    internal void ResetStaticLine()
    {
        if(TempObj!=null)
        {
            Destroy(TempObj);
            TempObj = null;
        }
    }

    //delete all lines
    internal void ResetLines()
    {
        foreach (Transform child in LineContainer)
        {
            Destroy(child.gameObject);
        }
    }
}
